export const USER_LIST_REQUEST = 'USER_LIST_REQUEST'
export const USER_LIST_SUCCESS = 'USER_LIST_SUCCESS'
export const USER_LIST_FAIL = 'USER_LIST_FAIL'
export const USER_LIST_RESET = 'USER_LIST_RESET'

export const USER_DELETE_REQUEST = 'USER_DELETE_REQUEST'
export const USER_DELETE_SUCCESS = 'USER_DELETE_SUCCESS'
export const USER_DELETE_FAIL = 'USER_DELETE_FAIL'
export const USER_DELETE_RESET = 'USER_DELETE_RESET'

export const USER_EDIT_REQUEST = 'USER_EDIT_REQUEST'
export const USER_EDIT_SUCCESS = 'USER_EDIT_SUCCESS'
export const USER_EDIT_FAIL = 'USER_EDIT_FAIL'
export const USER_EDIT_RESET = 'USER_EDIT_RESET'

export const USER_ADMIN_PROFILE_REQUEST = 'USER_ADMIN_PROFILE_REQUEST'
export const USER_ADMIN_PROFILE_SUCCESS = 'USER_ADMIN_PROFILE_SUCCESS'
export const USER_ADMIN_PROFILE_FAIL = 'USER_ADMIN_PROFILE_FAIL'
export const USER_ADMIN_PROFILE_RESET = 'USER_ADMIN_PROFILE_RESET'

export const PRODUCT_DELETE_REQUEST = 'PRODUCT_DELETE_REQUEST'
export const PRODUCT_DELETE_SUCCESS = 'PRODUCT_DELETE_SUCCESS'
export const PRODUCT_DELETE_FAIL = 'PRODUCT_DELETE_FAIL'
export const PRODUCT_DELETE_RESET = 'PRODUCT_DELETE_RESET'

export const PRODUCT_CREATE_REQUEST = 'PRODUCT_CREATE_REQUEST'
export const PRODUCT_CREATE_SUCCESS = 'PRODUCT_CREATE_SUCCESS'
export const PRODUCT_CREATE_FAIL = 'PRODUCT_CREATE_FAIL'
export const PRODUCT_CREATE_RESET = 'PRODUCT_CREATE_RESET'

export const PRODUCT_UPDATE_REQUEST = 'PRODUCT_UPDATE_REQUEST'
export const PRODUCT_UPDATE_SUCCESS = 'PRODUCT_UPDATE_SUCCESS'
export const PRODUCT_UPDATE_FAIL = 'PRODUCT_UPDATE_FAIL'
export const PRODUCT_UPDATE_RESET = 'PRODUCT_UPDATE_RESET'  

export const PRODUCT_ADMIN_DETAIL_REQUEST = 'PRODUCT_ADMIN_DETAIL_REQUEST'
export const PRODUCT_ADMIN_DETAIL_SUCCESS = 'PRODUCT_ADMIN_DETAIL_SUCCESS'
export const PRODUCT_ADMIN_DETAIL_FAIL = 'PRODUCT_ADMIN_DETAIL_FAIL'
export const PRODUCT_ADMIN_DETAIL_RESET = 'PRODUCT_ADMIN_DETAIL_RESET'  